[package]
name = "flipstargamer/middleman"
version = "1.0.1"
description = "A easy to use script-based client server communicator"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/**", "default.project.json", "wally.toml", "LICENSE"]

[dependencies]
